### PR TITLE
fix(diesel-price): Fix Submodule

### PR DESCRIPTION
**Pull request by riccardopersiani**
Please @gitmp01, could you review the code?

### CODE REVIEW

**Comment by gitmp01** [comment]
Look that the oraclize submodule commit pointed by [dieselPrice](https://github.com/oraclize/eos-examples/tree/fix/diesel-price-submodule/diesel-price) and the others examples (like [this one](https://github.com/oraclize/eos-examples/tree/fix/diesel-price-submodule/eos-usd-price)) are not the same. Should they?

**Comment by riccardopersiani** [comment]
Good catch! 

All the current submodules in `master` - except the diesel-price example - are pointing to an older version of the api, which is not correct.

@gitmp01 @D-Nice @gskapka Since it's not very efficient to update these submodules, do you guys think is it better to drop them, or still make sense to keep them? 

None of the above solutions is really user friendly in my opinion: 

* with submodules, users will have to clone with `--recursive`

```
PRO: everything is already setup.
CONS: clone with `--recursive` , which for sure someone will miss.
CONS: examples won't work correctly, if submodule is old.
```

* without submodules, user will have to download manually the `eos-api` project repo, since eos doesn't allow import from GitHub as we do on ethereum, and rename the folder to "oraclize".

```
PRO: impossible to download a wrong version of the `eos_api.hpp`.
CONS: someone could miss the folder renaming.
```

**Comment by gitmp01** [comment]
Another sol would be to move one level above the eos-api (as a submodule) and write into the readme to copy it into the example

**Comment by gskapka** [comment]
This is the other annoying thing about submodules - they remain at whatever commit they were at when you added them to the mother-repo. Additonal changes to the submodules do not propagate upwards.

So now you have two sources of truth as it were, and that makes for mistakes, as @D-Nice & I just experienced...

The submodule method is a flawed/non-intuitive/painful way of adding repos inside repos.

**Comment by gitmp01** [comment]
> _This is the other annoying thing about submodules - they remain at whatever commit they were at when you added them to the mother-repo. Additonal changes to the submodules do not propagate upwards._

Actually, I think this is a feature. If the upgrade is done automatically the changes could break the code using the submodule itself. Keeping the commit fixed instead, it would work always as the last time you've tested it.

**Comment by gitmp01** [comment]
@riccardopersiani so, in the end, I still support submodules, but I think you should keep only one, without having the pain of the redundancy of the current version. Just put it in the root of the project and that's it.

**Comment by gskapka** [comment]
> Actually, I think this is a feature.

It is indeed a feature, but I think most people reach to submodules for the use-case of needing a repo inside a repo. And for this usecase, it's usually because they want to work with that inner repo and have the changes propagate to the upstream repo, which with submodules they do not do. 

Again, they're kinda unintuitive.

**Comment by riccardopersiani** [comment]
Thanks guys, discussion was really useful.

PR closed due another PR created to cleanly merge submodule updates and fixes.

**Pull request closed without merging**
